# Generated by Django 6.0.6 on 2026-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, help_text='Bot token from @BotFather', max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='Public HTTPS base URL of the backend, e.g. https://api.example.com')),
                ('is_webhook_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram bot',
                'verbose_name_plural': 'Telegram bot',
            },
        ),
    ]
