# Generated by Django 6.0.6 on 2026-06-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='promo_code',
        ),
    ]
