# Generated by Django 6.0.6 on 2026-06-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_remove_discount_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='claimeddiscount',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claimeddiscount',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='claimeddiscount',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claimeddiscount',
            name='claimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimeddiscount',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
