# Generated by Django 6.0.6 on 2026-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_remove_studentprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
