# Generated by Django 6.0.6 on 2026-08-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='campus.place'),
        ),
    ]
