# Generated by Django 6.0.6 on 2026-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_partner_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
