# Generated by Django 6.0.6 on 2026-08-03 06:11

import uuid

from django.db import migrations, models


def assign_unique_tokens(apps, schema_editor):
    StudentProfile = apps.get_model('campus', 'StudentProfile')
    for profile in StudentProfile.objects.all():
        profile.verification_token = uuid.uuid4()
        profile.save(update_fields=['verification_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_studentprofile_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
        migrations.RunPython(assign_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
