# Generated by Django 6.0.6 on 2026-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_studentprofile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='deal_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('one_time', 'One-time')], default='regular', max_length=20),
        ),
    ]
