# Generated by Django 6.0.6 on 2026-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_promovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='place_images/'),
        ),
    ]
