# Generated by Django 6.0.6 on 2026-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_fix_image_url_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promovideo',
            name='url',
        ),
        migrations.AddField(
            model_name='promovideo',
            name='file',
            field=models.FileField(blank=True, upload_to='promo_videos/'),
        ),
    ]
