# Generated by Django 6.0.6 on 2026-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_remove_promovideo_url_promovideo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_card_image',
            field=models.ImageField(blank=True, upload_to='student_cards/'),
        ),
    ]
